### PR TITLE
Adds support for Next.JS and Gatsby

### PR DESCRIPTION
**Pull request by aleccool213**
- Simply adds a flag to not run the code when `window` is not defined
- This is a crude, simple solution that is not elegant
  - Likely a better solution to this
- This is just to get it working for my personal blog which uses GatsbyJS
- I have not tested with Next.JS

### CODE REVIEW

**Comment by sandoche** [comment]
Have you tried to replace `window` with `this` ?
It should work according to @frenco https://github.com/sandoche/Darkmode.js/issues/15#issuecomment-516090228

**Comment by aleccool213** [comment]
@sandoche No, I read that and wasn't convinced that is the correct solution. Do you have any insight into why that would be better? `IS_BROWSER` is very clear to the reader.

**Comment by sandoche** [comment]
Why did you change the linting rules ?

**Comment by aleccool213** [comment]
@sandoche Sorry about that! I accidentally committed it. I pushed up my changes without the eslint changes.

**Comment by adithwip** [comment]
Been waiting for this PR to merge 😅

**Comment by sandoche** [comment]
Yes sorry I didn't have the time yet.
I will check this out this weekend!

**Comment by sandoche** [comment]
@adithwip Branch finally merged!
@aleccool213 THanks for this amazing fix!

**Comment by adithwip** [comment]
Amazing! 
Thanks for the fix @aleccool213 
And thanks for this marvelous project @sandoche

**Pull request merged**
